plugins {
    id 'dev.architectury.loom' version '1.7-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
    id 'me.modmuss50.mod-publish-plugin' version '1.1.0'
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        // Set up a suffixed format for the mod jar names, e.g. `example-fabric`.
        archivesName = "$rootProject.archives_name-$project.name"
    }

    repositories {
        maven { url = "https://mvn.devos.one/releases" } // Porting Lib releases
        maven { url = "https://mvn.devos.one/snapshots" } // Create and several dependencies
        maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
        maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" } // Forge Config API Port
        maven {
            url = "https://api.modrinth.com/maven"
        }
        maven { url = "https://maven.terraformersmc.com/releases/" }
        maven { url = "https://cursemaven.com" }
        maven { url = "https://maven.tterrag.com/" } // Flywheel
        maven { // Fabric ASM for Porting Lib
            url = "https://jitpack.io/"
            content { includeGroupAndSubgroups("com.github") }
        }
    }

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.officialMojangMappings()
    }

    java {
        // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
        // if it is present.
        // If you remove this line, sources will not be generated.
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }

    // Configure Maven publishing.
    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }

        // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
        repositories {
            // Add repositories to publish to here.
            // Notice: This block does NOT have the same function as the block in the top level.
            // The repositories here will be used for publishing your artifact, not for
            // retrieving dependencies.
        }
    }
}

// Mod Publishing
def publishingFile = file("publishing.properties")
if (!publishingFile.exists()) {
    throw new InvalidUserDataException("publishing.properties could not be found.")
}
def publishing = new Properties()
publishingFile.withInputStream { publishing.load(it) }
publishing.each { k, v -> if (v != null) publishing.setProperty(k, v.toString().trim()) }

publishMods {
    changelog = file("CHANGELOG.md").exists() ? file("CHANGELOG.md").text : "Changelog not found - check the repository for updates."
    type = project.version.toString().toLowerCase().contains("pre") ? BETA : STABLE
    maxRetries = 5

    def cfOptions = curseforgeOptions {
        accessToken = providers.provider({ publishing.getProperty("curseforgeToken") })
        projectId = publishing.getProperty("curseforgeId")
        minecraftVersions.add(project.minecraft_version)
        projectSlug = "building-but-better"
    }

    def mrOptions = modrinthOptions {
        accessToken = providers.provider({ publishing.getProperty("modrinthToken") })
        projectId = publishing.getProperty("modrinthId")
        minecraftVersions.add(project.minecraft_version)
    }

    curseforge("curseforgeFabric") {
        from cfOptions
        file project(":fabric")
        modLoaders.add("fabric")
        requires("architectury-api")
        displayName = "Building But Better ${project.version} (Fabric ${project.minecraft_version})"
    }

    curseforge("curseforgeForge") {
        from cfOptions
        file project(":forge")
        modLoaders.add("forge")
        requires("architectury-api")
        displayName = "Building But Better ${project.version} (Forge ${project.minecraft_version})"
    }

    modrinth("modrinthFabric") {
        from mrOptions
        file project(":fabric")
        modLoaders.add("fabric")
        requires("architectury-api")
        displayName = "Building But Better ${project.version} (Fabric ${project.minecraft_version})"
    }

    modrinth("modrinthForge") {
        from mrOptions
        file project(":forge")
        modLoaders.add("forge")
        requires("architectury-api")
        displayName = "Building But Better ${project.version} (Forge ${project.minecraft_version})"
    }
}
